# ------- ESPHome defaults for your board go here -------

# Unused deep_sleep block to prevent the sensors from showing as "unavailable" when the sun goes down.
deep_sleep:
  id: fake_deep_sleep

# During the first hours of the day, the inverter can power on and off multiple times per minute until there is enough sunlight.
# We don't want this to trigger safe-mode and possibly delay any valid readings.
safe_mode:
  disabled: True

# Required for total_daily_energy.
time:
  - platform: sntp

# Configuration for the UART bus. Change the pin assignments as needed for your board.
uart:
  id: uart_1
  rx_pin: GPIO06
  tx_pin: GPIO07
  baud_rate: 9600

# Configuration for the MODBUS client over UART.
modbus:
  id: modbus_1
  uart_id: uart_1
  role: client

# Configuration for the device (inverter) on the MODBUS bus.
modbus_controller:
  - id: modbus_device
    address: 0x1
    modbus_id: modbus_1
    setup_priority: -10

sensor:
  # ESP32's internal temperature. Optional and can be removed if your board doesn't support it.
  - platform: internal_temperature
    name: "Internal Temperature"

  # Active power in W, measured in increments of 10W.
  - platform: modbus_controller
    id: active_power
    modbus_controller_id: modbus_device
    name: "Active Power"
    device_class: power
    accuracy_decimals: 0
    register_type: read
    address: 3004
    unit_of_measurement: "W"
    value_type: U_DWORD

  # The total power generated by the inverter in its entire lifetime.
  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Total Power"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 0
    register_type: read
    address: 3008
    unit_of_measurement: "kWh"
    value_type: U_DWORD

  # The amount of power generated today. Very innacurate and inadequate for cloudy days where production is small.
  # Kept here for the sake of having the value available if needed.
  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Generation Today (reported)"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    register_type: read
    address: 3014
    unit_of_measurement: "kWh"
    value_type: U_WORD
    filters:
      - multiply: 0.1

  # Same as above, but aggregated from the active power over time. Much more accurate and suitable for use in the Energy dashboard.
  - platform: total_daily_energy
    power_id: active_power
    restore: false
    name: "Generation Today (calculated)"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 2
    unit_of_measurement: "Wh"

  # Power generated on the previous day as reported by the inverter.
  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Generation Yesterday"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 1
    register_type: read
    address: 3015
    unit_of_measurement: "kWh"
    value_type: U_WORD
    filters:
      - multiply: 0.1

  # All the sensors down from here should be pretty self-explanatory

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "DC Output Power"
    device_class: power
    state_class: measurement
    accuracy_decimals: 0
    register_type: read
    address: 3006
    unit_of_measurement: "W"
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Generation This Month"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 0
    register_type: read
    address: 3010
    unit_of_measurement: "kWh"
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Generation Last Month"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 0
    register_type: read
    address: 3012
    unit_of_measurement: "kWh"
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Generation This Year"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 0
    register_type: read
    address: 3016
    unit_of_measurement: "kWh"
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Generation Last Year"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 0
    register_type: read
    address: 3018
    unit_of_measurement: "kWh"
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "DC Voltage"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    register_type: read
    address: 3021
    unit_of_measurement: "V"
    value_type: U_WORD
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "DC Current"
    device_class: current
    state_class: measurement
    accuracy_decimals: 1
    register_type: read
    address: 3022
    unit_of_measurement: "A"
    value_type: U_WORD
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "AC Voltage"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    register_type: read
    address: 3035
    unit_of_measurement: "V"
    value_type: U_WORD
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "AC Current"
    device_class: current
    state_class: measurement
    accuracy_decimals: 1
    register_type: read
    address: 3038
    unit_of_measurement: "A"
    value_type: U_WORD
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Grid Frequency"
    device_class: frequency
    state_class: measurement
    accuracy_decimals: 2
    register_type: read
    address: 3042
    unit_of_measurement: "Hz"
    value_type: U_WORD
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Inverter Temperature"
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 1
    register_type: read
    address: 3041
    unit_of_measurement: "°C"
    value_type: U_WORD
    filters:
      - multiply: 0.1
